### ISSUE TITLE
HttpParser won't build properly on gcloud instance

### ISSUE THREAD

**Issue by macrintr** [seung-lab/BigArrays.jl#22]
Using Ubuntu14.04 native gcloud instance. Using julia-0.5.2. Adding GoogleCloud.jl requires HttpParser, which won't build, leaving this error message:

```
LoadError: could not spawn `unzip -x /home/thomas_macrina/.julia/v0.5/HttpParser/deps/downloads/v2.7.1.zip -d /home/thomas_macrina/.julia/v0.5/HttpParser/deps/src`: no such file or directory (ENOENT)
while loading /home/thomas_macrina/.julia/v0.5/HttpParser/deps/build.jl, in expression starting on line 71
```

Unable to track down exactly what the problem is on the interweb.

**Comment by jingpengw** [comment]
Probably the `unzip` was not installed. Should be an issue of HttpParser, close here.
